steps:
  - label: "Build Image"
    command: "docker build . -t karthikkrish84/myreactapp:latest; docker push karthikkrish84/myreactapp:latest"
    plugins:
      - docker#v5.3.0:
          image: "docker:latest"